### PR TITLE
:white_check_mark: Fixed bug with season endpoint returning incorrect items when continuing flag specified

### LINKED ISSUE #555: 🐛 Season endpoint returns items which don't belong to season
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Re:zero 3'rd season is being included in seasons of 2024 other than fall.
You can see it happening here: https://api.jikan.moe/v4/seasons/2025/winter?filter=tv&continuing&page=1

### Expected Behavior

Re:zero 3rd season should only appear for 2024 fall, and if it still has unknown ending air time, and the current date falls under a future season, then it should be included in that season too, but not before.

### Steps To Reproduce

_No response_

### Environment

```markdown
- Both Self hosted and public api
- Ubuntu 22.04
- PHP 8.1
```

### Anything else?

Recently I've added the "continuing" option for the season api endpoint which would include left over / continuing items. This flag doesn't behave correctly at the moment.
The mongodb query should consider also the current date and which season that date corresponds to when looking for items.

The problem is here: https://github.com/jikan-me/jikan-rest/blob/master/app/Repositories/DefaultAnimeRepository.php#L147-L189

### PR DESCRIPTION
**Pull request by pushrbx**
Fixes #555 

The filter predicate for mongodb was incorrect, it included also those items when `continuing` filter flag was present which are from the same month as the month of the `$from` date calculated based on the season endpoint request.

This PR fixes that issue, also added a test to validate it.

### CODE REVIEW

File: tests/Integration/SeasonControllerTest.php [hunk 1]
```diff
@@ -190,4 +190,39 @@ public function testShouldNotIncludeContinuingItemsByDefault()
...
+        $carbonStartDate = Carbon::parse($startDate);
+        $state = $f->serializeStateDefinition([
+            "aired" => new CarbonDateRange($carbonStartDate, null)
+        ]);
+        $state["aired"]["string"] = "Oct 2, 2024 to ?";
+        $state["airing"] = true;
+        $state["status"] = "Currently Airing";
+        $state["premiered"] = "Fall 2024";
+        $state["mal_id"] = 54857;
+        $state["title"] = "Re:Zero kara Hajimeru Isekai Seikatsu 3rd Season";
```
Comment (irfan-dahir) [inline tests/Integration/SeasonControllerTest.php:208]: Wouldn't this test pass in any case in the future?

File: app/Repositories/DefaultAnimeRepository.php
Comment (irfan-dahir) [inline app/Repositories/DefaultAnimeRepository.php:1]: This code was added previously;

```
'episodes' => ['$gte' => 14],
```

Could you explain this check to me? Would 14 be the correct check here?

File: app/Producers.php
Comment (irfan-dahir) [inline app/Producers.php:1]: Do we need the same thing for Producers?

File: app/Repositories/DefaultAnimeRepository.php [hunk 2]
```diff
@@ -167,19 +167,39 @@ public function getItemsBySeason(
                 $finalFilter['$or'][] = [
                     // note: this expression only works with mongodb version 5.0.0 or higher
                     '$expr' => [
-                        '$lte' => [
+                        '$and' => [
```
Comment (irfan-dahir) [inline app/Repositories/DefaultAnimeRepository.php:170]: Rezero's 3rd season is still being returned in fall 2025 with this request:
`/v4/seasons/2025/winter?filter=tv&continuing&page=1`

 But doesn't this make sense given it's comprised of 16 episodes?

File: app/Repositories/DefaultAnimeRepository.php
Comment (pushrbx) [reply app/Repositories/DefaultAnimeRepository.php:1]: This is used to measure whether the anime would go over to another season. Usually the max number of episodes in a  season is 14.

File: tests/Integration/SeasonControllerTest.php (hunk 1 above)
Comment (pushrbx) [reply tests/Integration/SeasonControllerTest.php:208]: Not sure what you are asking. Are you asking about the mocks in the test or in overall?

File: app/Producers.php
Comment (pushrbx) [reply app/Producers.php:1]: I'll check it whether typesense is itchy about it, and I'll add it if yes. I've added this to make the migration of "collections" in typesense more smooth.

File: app/Repositories/DefaultAnimeRepository.php (hunk 2 above)
Comment (pushrbx) [reply app/Repositories/DefaultAnimeRepository.php:170]: This is not the case for my self-hosted version. I already have this version deployed. I'll send you a link to it to check, so we can reproduce it if this is the case.

File: tests/Integration/SeasonControllerTest.php (hunk 1 above)
Comment (irfan-dahir) [reply tests/Integration/SeasonControllerTest.php:208]: I meant overall, missed that this would be the mock tests. In that case the data would be static so it sounds A-OK.

File: app/Repositories/DefaultAnimeRepository.php
Comment (irfan-dahir) [reply app/Repositories/DefaultAnimeRepository.php:1]: Gotcha

**Review by irfan-dahir — APPROVED** [review]

**Review by irfan-dahir — APPROVED** [review]
