### PR TITLE
Added fixes for searching and various things

### LINKED ISSUE #411: 🐛  Looking up some profiles or user with uppercased username will throw 404
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If a user with uppercased username (`ExampleMal123`) want to lookup their profile via Jikan on `/users/<username>/*` endpoint, Jikan will throw 404 Not Found error instead.

### Expected Behavior

A data should be returned whatever the case it is, as long it exists in MyAnimeList.

### Steps To Reproduce

1. Open any terminal with `curl`, `wget`, or `Invoke-WebRequest`. For familiarity to write this issue, I use PowerShell with `Invoke-WebRequest`
2. Do a GET method to `https://api.jikan.moe/v4/users/<username>` with `<username>` is user target with uppercased title
   * Cmdlet will return 404 Not Found error:

     ```pwsh
	 $jikan_test = iwr "https://api.jikan.moe/v4/users/ExampleMal123" -UseBasicParsing
	 Invoke-WebRequest: The remote server returned an error: (404) Not Found.
	 At line:1 char:15
	 + ... ikan_test = iwr "https://api.jikan.moe/v4/users/ExampleMal123" -UseBasic ...
	 +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebException
     + FullyQualifiedErrorId : WebCmdletWebResponseException,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
	 ```
3. Try to do the same, but with lowercase:
   ```pwsh
   PS > $jikan_test = iwr "https://api.jikan.moe/v4/users/examplemal123" -UseBasicParsing
   PS > $jikan_test
   
   
   StatusCode        : 200
   StatusDescription : OK
   Content           : {"data":{"mal_id":12345,"username":"ExampleMal123","url":"https:\/\/myanimelist.net\/profile\/ExampleMal123","images":{"jpg":{"image_url":"https:\/\/cdn.myanimelist.net\/s\/common\/userimages\/da6ea047-d3...
   RawContent        : HTTP/1.1 200 OK
                       Transfer-Encoding: chunked
                       Connection: keep-alive
                       x-request-fingerprint: request:users:123456
                       access-control-allow-origin: *
                       Vary: Accept-Encodin...
   Forms             :
   Headers           : {[Transfer-Encoding, chunked], [Connection, keep-alive], [x-request-fingerprint,request:users:123456], [access-control-allow-origin,*]...}
   Images            : {}
   InputFields       : {}
   Links             : {}
   ParsedHtml        :
   RawContentLength  : 580
   ```

### Environment

```markdown
Used public API

Tested on:
* Windows PowerShell 5
* Python 3.10 AioHTTP 3.8.4
* Brave 1.52.126 Chromium: 114.0.5735.133 (Official Build) (64-bit)
```

### Related Issue/Context
* [#"Some users returns Not Found" forum thread on #bug-reports](https://discord.com/channels/460491088004907029/1119913255545077760)

### Mitigation
Developer of 3rd party can mitigate this bug by hardcode lowercasing to avoid unwanted error

### PR DESCRIPTION
**Pull request by pushrbx**
- Better typesense 0.24.1 support
- Exhaustive search disabled by default
- Added central place for the MAX_RESULTS_PER_PAGE option
  - In the future we should strive for the "options" pattern, where a class represents the configuration options of the app and applies safe defaults in the correct type.
  - Added `max_results_per_page()` helper function as part of this fix.
- Added class for getting searchable attributes of models in typesense
- Added basic search analytics:
  - The default implementation saves the search terms and the first page of hits and hit count in the database, and indexes the search term in Typesense.
  - Indexing the search terms used by users will later help with adding new features. (E.g. search suggestions)
- Fixed tests
- Fixed an issue with the `/v4/schedules/<dayFilter>` request validator.
- Fixed deprecation logger
- Fixed bug with ordering through the search engine. E.g. `?q=searchterm&order_by=score` would not order by `score`, rather by the default sort order.
- Fixed #411 

Exhaustive search disabled means that typesense will eat less system resources, but the number of hits will decrease, but the quality of relevance won't be affected.
I think with earlier versions of typesense we used exhaustive search to have enough hits. However the latest version already returns enough hits with exhaustive search turned off for most of the use cases. Only the `drop_tokens_threshold` and `typo_tokens_threshold` needs to be tweaked, and we can get good enough results I think.

Might fixes these issues:
- #393 
- #401 
- #396

### CODE REVIEW

**Comment by Wamy-Dev** [comment]
Searching `Girls & Panzer` doesn't bring up anything, but searching `Panzer` does. 

`Girls and Panzer` also doesn't work.

File: app/Anime.php [hunk 1]
```diff
@@ -381,13 +381,17 @@ public function getSearchIndexSortBy(): array|null
...
         return [
             [
-                "field" => "_text_match",
+                "field" => "_text_match(buckets:" . max_results_per_page() . ")",
                 "direction" => "desc"
             ],
             [
-                "field" => "members",
-                "direction" => "desc"
+                "field" => "popularity",
```
Comment (irfan-dahir) [inline app/Anime.php:388]: Popularity is based on members. So we could just use that

File: app/Rules/MaxResultsPerPageRule.php [hunk 2]
```diff
@@ -36,11 +37,7 @@ public function passes($attribute, $value): bool
 
     public function message(): array|string
     {
-        return "Value {$this->value} is higher than the configured '{$this->maxResultsPerPage()}' max value.";
```
Comment (irfan-dahir) [inline app/Rules/MaxResultsPerPageRule.php:39]: Will this be thrown as an API response error?

**Review by irfan-dahir — CHANGES_REQUESTED** [review]

File: app/Anime.php (hunk 1 above)
Comment (pushrbx) [reply app/Anime.php:388]: this one gives better results tho

File: app/Rules/MaxResultsPerPageRule.php (hunk 2 above)
Comment (pushrbx) [reply app/Rules/MaxResultsPerPageRule.php:39]: This is a request validation rule, which prevents users to specify higher value for the `limit` parameter than the configured value in the configuration.

**Comment by pushrbx** [comment]
> > Only the drop_tokens_threshold and typo_tokens_threshold needs to be tweaked, and we can get good enough results I think.
> 
> Do you think we should add these to `.env.dist`?

Only if we want to fully support the tweaking of it for not so hardcore users.

File: app/Anime.php (hunk 1 above)
Comment (irfan-dahir) [reply app/Anime.php:388]: Huh interesting

**Review by irfan-dahir — APPROVED** [review]

**Comment by irfan-dahir** [comment]
LGTM
