### PR TITLE
Exception Handling enhancement

### LINKED ISSUE #269: getAnimeStatistics times out frequently
Over the span of 9 minutes, I made 83 requests to `GET /anime/:id/statistics`. Of these, 7 failed with "408 Request Timeout" errors.

Within the same time span I made 83 requests to `GET /anime/:id` and they all succeeded. So this issue seems to affect statistics specifically.

An example error response body is

```json
{
    "status": 408,
    "type": "TimeoutException",
    "message": "Request to MyAnimeList.net timed out (10 seconds)",
    "error": "Idle timeout reached for \"https:\/\/myanimelist.net\/anime\/579\/jikan\/stats\"."
}
```

A request a few minutes later for this same anime took 2 seconds to complete successfully.

A few extra notes:

 - 408 Request Timeout is a 4xx error, which means it indicates the fault lies with the client. Because the issue here is happening on Jikan's end, Jikan should return a 5xx error. Typically 504 Gateway Timeout is returned when an upstream server fails to respond in a timely manner.
 - The error response mentions a 10 second timeout, but the error seems to consistently happen after 60-63 seconds or 120-123 seconds. (Of my 7 failed requests, 2 took between 120-123 seconds, the other 5 took between 60-63 seconds)

### PR DESCRIPTION
**Pull request by irfan-dahir**
- Replaces all upstream `type` in response JSON to `UpstreamException`
- `TimeoutException`, `TransportException`, Blank Responses will now return HTTP 500 and `UpstreamException`
- Dispatches Bad `SourceHeartbeatEvent` for `TimeoutException` and `TransportException`
- HTTP 429 response exception type updated `BadResponseException` -> `RateLimitException`
- Updated error messages and docs
- Should resolve #269 , #343 , #314, #339

### CODE REVIEW

File: app/Exceptions/Handler.php [hunk 1]
```diff
@@ -153,51 +153,55 @@ public function render($request, \Throwable $e): JsonResponse|Response
                     return response()
                         ->json([
                             'status' => $e->getCode(),
-                            'type' => 'BadResponseException',
-                            'message' => 'Jikan failed to connect to MyAnimeList.net. MyAnimeList.net may be down/unavailable, refuses to connect or took too long to respond.',
+                            'type' => 'UpstreamException',
+                            'message' => 'Request to MyAnimeList.net failed. MyAnimeList.net may be down/unavailable, refuses to connect or took too long to respond. Please try again later.',
                             'error' => $e->getMessage()
-                        ], 503);
+                        ], 504);
```
Comment (pushrbx) [inline app/Exceptions/Handler.php:159]: This should be 500. In terms of REST API and the client's request to Jikan API, 504 doesn't make sense, because the client's request was received by the app. The timeout happened with an upstream service, and all http apps return 500 in those cases, that's the standard.

File: app/Exceptions/Handler.php [hunk 2]
```diff
@@ -153,51 +153,55 @@ public function render($request, \Throwable $e): JsonResponse|Response
...
                 ->json([
-                    'status' => 408,
-                    'type' => 'TimeoutException',
-                    'message' => 'Request to MyAnimeList.net timed out (' .env('SOURCE_TIMEOUT', 5) . ' seconds)',
+                    'status' => 504,
+                    'type' => 'UpstreamException',
+                    'message' => 'Request to MyAnimeList.net timed out (' .env('SOURCE_TIMEOUT', 5) . ' seconds). Please try again later.',
                     'error' => $e->getMessage()
-                ], 408);
+                ], 504);
```
Comment (pushrbx) [inline app/Exceptions/Handler.php:180]: This should be 500.

File: app/Exceptions/Handler.php [hunk 3]
```diff
@@ -153,51 +153,55 @@ public function render($request, \Throwable $e): JsonResponse|Response
...
                 ->json([
-                    'status' => 500,
-                    'type' => 'TransportException',
-                    'message' => 'Request to MyAnimeList.net has failed. The upstream server has returned a non-successful status code.',
+                    'status' => 504,
+                    'type' => 'UpstreamException',
+                    'message' => 'Request to MyAnimeList.net failed. MyAnimeList.net may be down/unavailable, refuses to connect or took too long to respond. Please try again later.',
                     'error' => $e->getMessage()
-                ], 500);
+                ], 504);
```
Comment (pushrbx) [inline app/Exceptions/Handler.php:192]: This should be 500.

File: app/Exceptions/Handler.php [hunk 4]
```diff
@@ -153,51 +153,55 @@ public function render($request, \Throwable $e): JsonResponse|Response
...
                 ->json([
-                    'status' => $e->getCode(),
-                    'type' => 'BadResponseException',
-                    'message' => 'Jikan failed to connect to MyAnimeList.net. MyAnimeList.net may be down/unavailable, refuses to connect or took too long to respond. Retry the request!',
+                    'status' => 504,
+                    'type' => 'UpstreamException',
+                    'message' => 'Request to MyAnimeList.net failed. MyAnimeList.net may be down/unavailable, refuses to connect or took too long to respond. Please try again later.',
                     'error' => $e->getMessage()
-                ], 503);
+                ], 504);
```
Comment (pushrbx) [inline app/Exceptions/Handler.php:204]: This should be 500.

**Review by pushrbx — CHANGES_REQUESTED** [review]

**Review by pushrbx — APPROVED** [review]
